# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
# Mod Properties
mod_version=1.0.0
maven_group=com.mikarific
archives_base_name=EIDTracker
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.149.0+26.1.2
malilib_version=0.28.3
minihud_version=0.39.2
tweakeroo_version=0.28.2
conditionalmixin_version = 0.6.4